services:
  frontend:
    image: node:22-alpine
    working_dir: "/app/01 - LOGIN"
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - "/app/01 - LOGIN/node_modules"
    command: sh -c "npm install && npm run dev -- --host"

  database:
    image: postgres:16
    environment:
      POSTGRES_DB: etp_db
      POSTGRES_USER: etp_user
      POSTGRES_PASSWORD: etp_password
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: