ALTER TABLE cursos
    ADD COLUMN nivel VARCHAR(30) NOT NULL DEFAULT 'Iniciante',
    ADD COLUMN duracao_minutos INT NOT NULL DEFAULT 0,
    ADD COLUMN icone VARCHAR(30) NOT NULL DEFAULT 'code',
    ADD COLUMN destaque BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN ordem_exibicao INT NOT NULL DEFAULT 1000;
